linters:
  Comment:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    convention: '^[a-z][-a-z0-9_]*$'

  MergeableSelector:
    force_nesting: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  SelectorDepth:
    enabled: false

  NameFormat:
    anabled: false

  Shorthand:
    enabled: true

  StringQuotes:
    style: double_quotes

  NameFormat:
    enabled: false

  SelectorFormat:
    enabled: false

  Comment:
    enabled: false

  UrlQuotes:
    enabled: false

  StringQuotes:
    style: single_quotes
